server:
  port: 8075
  # 请求最大数据
  max-http-header-size: 10485760
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  # tomcat配置
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      encoding: UTF-8
      enabled: true
      file-date-format: yyyy-MM-dd
spring:
  # 邮件发送
  mail:
    username: 2185067708@qq.com
    password: tecypwxmysrbeajj
    host: smtp.qq.com
    default-encoding: UTF-8
    port: 25
    properties:
      mail:
        debug: false
        smtp:
          ssl:
            enbale: true
            socketFactory:
              class: javax.net.ssl.SocketFactory
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/MusicWebsite?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: tanx
    password: abc123

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.tanx.music.pojo
