server:
  tomcat:
    max-http-form-post-size: 30MB
spring:
  profiles:
    active: prod
  # 数据库(活跃的yaml文件会覆盖这个datasource)
  datasource:
    platform: mysql
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  main:
    allow-bean-definition-overriding: true